openapi: 3.0.3
info:
  title: Services
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://services.test'
paths:
  /api/login:
    post:
      summary: 'Login the user to their account'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Authentication APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The user''s email address'
                  example: voluptatem
                password:
                  type: string
                  description: 'The user''s password'
                  example: quasi
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: 'Register New User.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Authentication APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                f_name:
                  type: string
                  description: 'The user''s first name'
                  example: et
                l_name:
                  type: string
                  description: 'The user''s last name'
                  example: repudiandae
                email:
                  type: string
                  description: 'The user''s email address'
                  example: ipsa
                phone_number:
                  type: string
                  description: 'The user''s phone number'
                  example: quisquam
                password:
                  type: string
                  description: 'The user''s password'
                  example: omnis
              required:
                - f_name
                - l_name
                - email
                - phone_number
                - password
      security: []
  /api/google/auth:
    post:
      summary: 'Social Login'
      description: 'Login through google'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - 'Authentication APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the user'
                  example: ipsam
                email:
                  type: string
                  description: 'The email of the user'
                  example: magni
                phone_number:
                  type: string
                  description: 'The user''s phone number'
                  example: voluptatem
                token:
                  type: string
                  description: 'A google provided token'
                  example: incidunt
                email_verified:
                  type: boolean
                  description: 'Whether the user email is verified'
                  example: true
              required:
                - name
                - email
      security: []
  /api/user:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/services:
    get:
      summary: 'Get all services.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - 'Services APIs'
      security: []
    post:
      summary: 'Add a new service.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - 'Services APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'The title of the new service'
                  example: repellat
                price:
                  type: string
                  description: 'The price of the new service'
                  example: aperiam
                location_lat:
                  type: string
                  description: 'The latitude location of the new service'
                  example: quisquam
                location_long:
                  type: string
                  description: 'The longitude location of the new service'
                  example: et
                description:
                  type: text
                  description: 'The description of the new service'
                  example: sapiente
              required:
                - title
                - price
                - location_lat
                - location_long
  '/api/services/{id}':
    put:
      summary: 'Update a service.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - 'Services APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'The title of the service'
                  example: nisi
                description:
                  type: string
                  description: 'The description of the service'
                  example: ipsa
                price:
                  type: string
                  description: 'The price of the service'
                  example: beatae
                location_lat:
                  type: string
                  description: 'The latitude location of the new service'
                  example: cumque
                location_long:
                  type: string
                  description: 'The longitude location of the new service'
                  example: quos
              required:
                - title
      security: []
    get:
      summary: 'Show service details.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - 'Services APIs'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Optional parameter. The id of the service'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: saepe
tags:
  -
    name: 'Authentication APIs'
    description: ''
  -
    name: Endpoints
    description: ''
  -
    name: 'Services APIs'
    description: ''
